name: Check examples/index.html

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "package*.json"
      - ".github/workflows/examples.yml"
      - "content/**/examples/**"
      - "scripts/reference-tables.*"
      - "scripts/coverage-report.*"
      - "coverage/**"
  pull_request:
    paths:
      - "package*.json"
      - ".github/workflows/examples.yml"
      - "content/**/examples/**"
      - "scripts/reference-tables.*"
      - "scripts/coverage-report.*"
      - "coverage/**"

jobs:
  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate examples/index.html
        run: npm run reference-tables

      - name: Ensure no git changes
        run: git diff --exit-code

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage files
        run: npm run coverage-report

      - name: Check for git changes
        id: check_changes_coverage_report
        run: |
          (git diff --exit-code) && true
          echo "exit-code=$(echo $?)" >> $GITHUB_OUTPUT

      - name: Update default branch with updated coverage report if changed
        if: github.ref == 'refs/heads/main' && steps.check_changes_coverage_report.outputs.exit-code != 0
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "chore: update coverage report page's last updated date
          Generated by ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          "
          git push origin main

      - name: Return exit code if not default branch
        if: github.ref != 'refs/heads/main'
        run: exit ${{ steps.check_changes_coverage_report.outputs.exit-code }}
