name: Trigger pull request creation for wai repository

on:
  pull_request:
    paths:
      - ".github/workflows/wai-trigger-pr.yml"
      - "scripts/wai-trigger-pr.js"
      - "package*.json"
      - "test/**"
      - "examples/**"
      - "!examples/landmarks/**"
      - "!examples/coding-template/**"
      - "README.md"

jobs:
  create-pr-wai:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run wai-trigger-pr script
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'wai-aria-practices',
              workflow_id: 'pr-create.yml',
              ref: 'master',
              inputs: {
                apg_branch: 'apg/' + ${{ github.head_ref }},
                apg_sha: ${{ github.event.pull_request.head.sha }},
                apg_pr_number: ${{ github.event.pull_request.number }}
              }
            })
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APG_BRANCH: ${{ github.head_ref }}
          APG_SHA: ${{ github.event.pull_request.head.sha }}
          APG_PR_NUMBER: ${{ github.event.pull_request.number }}
